import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
plt.style.use('ggplot')
warnings.filterwarnings('ignore')
df = pd.read_csv("IPL.csv")
print("Dataset Shape:", df.shape)
df['superover_winner'] = df['superover_winner'].fillna("None")
df['result_type'] = df['result_type'].fillna("Normal")
matches = df.drop_duplicates(subset=['event_match_no', 'season'])
team_wins = matches['match_won_by'].value_counts()
print("\n=== Most Winning Teams ===")
print(team_wins.head(10))
plt.figure(figsize=(10,5))
team_wins.head(10).plot(kind='bar')
plt.title("Top Winning Teams")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
top_batsmen = df.groupby('batter')['batter_runs'].sum() \
                .sort_values(ascending=False).head(10)
print("\n=== Top 10 Batsmen ===")
print(top_batsmen)
plt.figure(figsize=(10,5))
top_batsmen.plot(kind='bar')
plt.title("Top Run Scorers")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
season_runs = df.groupby(['season', 'batter'])['batter_runs'].sum().reset_index()
top_season_batsman = season_runs.loc[
    season_runs.groupby('season')['batter_runs'].idxmax()
]
print("\n=== Best Batsman by Season ===")
print(top_season_batsman)
season_total = df.groupby('season')['team_runs'].sum().reset_index()
plt.figure(figsize=(10,5))
sns.barplot(x='season', y='team_runs', data=season_total)
plt.title("Total Runs per Season")
plt.xticks(rotation=45)
plt.show()
over_runs = df.groupby('over')['team_runs'].sum()
plt.figure(figsize=(10,5))
over_runs.plot(kind='line', marker='o')
plt.title("Run Distribution Across Overs")
plt.xlabel("Over")
plt.ylabel("Runs")
plt.grid()
plt.show()
total_wickets = df['striker_out'].sum()
avg_wickets = total_wickets / df['event_match_no'].nunique()
print("\n=== Wickets ===")
print("Total Wickets:", total_wickets)
print("Avg Wickets per Match:", round(avg_wickets, 2))
toss_match = matches[matches['toss_winner'] == matches['match_won_by']]
toss_percentage = (toss_match.shape[0] / matches.shape[0]) * 100
print("\n=== Toss Impact ===")
print(f"Toss Win -> Match Win: {toss_percentage:.2f}%")
home_wins = matches[matches['match_won_by'] == matches['batting_team']].shape[0]
away_wins = matches[matches['match_won_by'] == matches['bowling_team']].shape[0]
print("\n=== Home vs Away ===")
print("Home Wins:", home_wins)
print("Away Wins:", away_wins)
plt.figure()
plt.pie([home_wins, away_wins],
        labels=['Batting First Win', 'Bowling First Win'],
        autopct='%1.1f%%')
plt.title("Batting vs Chasing Wins")
plt.show()
top_partnerships = df.groupby('batting_partners')['batter_runs'] \
                     .sum().sort_values(ascending=False).head(10)

print("\n=== Top Partnerships ===")
print(top_partnerships)
plt.figure(figsize=(10,5))
top_partnerships.plot(kind='barh')
plt.title("Top Partnerships")
plt.gca().invert_yaxis()
plt.show()
matches['season'] = pd.to_numeric(matches['season'], errors='coerce')
matches = matches.dropna(subset=['season'])
matches_per_season = matches['season'].value_counts().sort_index()
plt.figure(figsize=(10,5))
matches_per_season.plot(kind='line', marker='o')
plt.title("Matches per Season")
plt.xlabel("Season")
plt.ylabel("Matches")
plt.grid()
plt.show()
print("\n" + "="*40)
print("FINAL INSIGHTS")
print("="*40)
print("- Certain teams dominate IPL historically.")
print("- Top batsmen consistently perform across seasons.")
print("- Death overs (16-20) show highest scoring.")
print("- Toss gives slight advantage (~50-55%).")
print("- Chasing vs defending outcomes are balanced.")
print("\nPROJECT COMPLETED ")